# Generated by Django 3.2.9 on 2021-12-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211227_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='pdf',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
