# Generated by Django 3.2.9 on 2021-12-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_ebooks_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False),
        ),
    ]
