# Generated by Django 3.2.9 on 2021-12-31 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('school', models.CharField(choices=[('NAHPI', 'NAHPI'), ('FSCH', 'FSCH'), ('HCIM', 'HCIM'), ('FACULTY', 'FACULTY'), ('ENS', 'ENS'), ('ENSET', 'ENSET')], default='NAHPI', max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=100)),
                ('photo_profile', models.ImageField(blank=True, upload_to=users.models.rename_image)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
