# Generated by Django 3.2.9 on 2021-12-31 15:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211231_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='staff member', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='matricule',
            field=models.CharField(default='staff member', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to=users.models.rename_image),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(choices=[('NAHPI', 'NAHPI'), ('FSCH', 'FSCH'), ('HCIM', 'HCIM'), ('FACULTY', 'FACULTY'), ('ENS', 'ENS'), ('ENSET', 'ENSET')], default='NAHPI', max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
