# Generated by Django 3.2.9 on 2022-01-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_ebooks_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooks',
            name='cover',
            field=models.ImageField(blank=True, upload_to='ecover'),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
