# Generated by Django 3.2.9 on 2022-01-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220114_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
