# Generated by Django 3.2.9 on 2022-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220126_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandbook',
            name='comand_date',
            field=models.DateTimeField(),
        ),
    ]
