# Generated by Django 3.2.9 on 2022-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_commandbook_comand_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandbook',
            name='comand_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
